name: Dendron site build

on:
  push:
    branches:
    - master
    - main
  pull_request:
    branches:
    - master
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    # Retain Node modules across builds
    - name: Restore Node modules cache
      uses: actions/cache@v2
      id: node-modules-cache
      with:
        path: |
          node_modules
          .next/node_modules
        key: node-modules-${{ hashFiles('yarn.lock')}}

    - name: Install npm dependencies
      run: yarn

    - name: Initialize .next
      run: yarn dendron publish init

    - name: Install dependencies
      run: cd .next && yarn && cd ..

    - name: Export notes
      run: yarn dendron publish build

    - name: Prep notes for publish
      run: ./publish.sh
